spring:
  config:
    activate:
      on-profile:
        - mariadb
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/legacy_custom?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: 1234

mybatis:
  mapper-locations:
    - classpath:mapper-mariadb/*.xml
